### ISSUE TITLE
点击Trade 跳转网页市集提示 “你所搜索的信息已不存在或是被移除了。”

### ISSUE THREAD

**Issue by Linpean** [Traveller-hongchen/Awakened-PoE-Trade-Simplified-Chinese#10]
貌似物品名词待变的编码规则发生了改变
查询“制图钉”的结果如下
国服网页市集链接：https://poe.game.qq.com/trade/search/S23%E8%B5%9B%E5%AD%A3/DB49RdS5
查价器市集链接：https://poe.game.qq.com/trade/search/S23%E8%B5%9B%E5%AD%A3/2oqVdoIk

**Comment by dongbuze** [comment]
我也是这样的,不知道为什么

**Comment by eliotefortoilet** [comment]
我也是

**Comment by Linpean** [comment]
8月30日已经能正常使用
