### ISSUE TITLE
国服查价显示的都是非一口价，愿添加能够选择交易类型

### ISSUE THREAD

**Issue by liwei8866** [Traveller-hongchen/Awakened-PoE-Trade-Simplified-Chinese#20]
国服查价显示的都是非一口价，原因是：交易类型里默认选择了“交易精确一口价”，改为任何后才能查到所有一口价物品，愿添加能够选择交易类型

**Comment by Traveller-hongchen** [comment]
下个版本会多一列标注出是否精准一口价（原本这个问题是国服市集的问题，但是现在它改了）
