### ISSUE TITLE
无法识别"安赛娜丝的安抚之语 丝绸手套"

### ISSUE THREAD

**Issue by Cthughaw** [Traveller-hongchen/Awakened-PoE-Trade-Simplified-Chinese#22]
![QQ图片20240104142058](https://github.com/Traveller-hongchen/Awakened-PoE-Trade-Simplified-Chinese/assets/155612573/52ae6bb1-e7f9-49f9-b4fc-603c248a13b5)

**Comment by Traveller-hongchen** [comment]
修了
