### ISSUE TITLE
插件使用过程中，一直显示查询中

### ISSUE THREAD

**Issue by AsongChen** [Traveller-hongchen/Awakened-PoE-Trade-Simplified-Chinese#27]
我直接查询商店并不存在问题，开了VPN 和 加速器。
但是在使用插件的过程中，一直提示已匹配，但是没有结果，重启后，可以有用一会儿，但是不久之后，就还是变成已匹配，但是没有结果

**Comment by Kilitao7** [comment]
你怎么自己关了，我也是这个问题，难道你解决了吗？请问怎么解决的。
