### ISSUE TITLE
赛季载入失败

### ISSUE THREAD

**Issue by 200645049** [Traveller-hongchen/Awakened-PoE-Trade-Simplified-Chinese#28]
赛季载入失败
物品价格搜索,请按错误信息指示操作

{"error":{"code":8,"message":"Unauthorized"}}

**Comment by 200645049** [comment]
哦  POESESSID 改为cookie了。。

**Comment by WxfEntity** [comment]
我也是这个问题，是cookie里的POESESSID ，还是cookie的key
