### ISSUE TITLE
【国服】使用集市中的搜索时输入问题

### ISSUE THREAD

**Issue by TokenYc** [Traveller-hongchen/Awakened-PoE-Trade-Simplified-Chinese#4]
感谢大佬的汉化和分享，目前使用中发现了一个问题：
在国服客户端中使用时，打开集市，搜索物品，或者筛选物品时，输入了拼音，按空格，无法正常输入文字。
输入法使用的是“搜狗输入法”

**Comment by Traveller-hongchen** [comment]
这跟我有啥关系？我只是一个做查价器的
