### ISSUE TITLE
版本3.21.10008

### ISSUE THREAD

**Issue by Depeteypan** [Traveller-hongchen/Awakened-PoE-Trade-Simplified-Chinese#8]
分析物品错误
有可能是一个BUG，请至GitHub提交错误

物品类别: 细剑
稀 有 度: 稀有
魔域 禁域
忆境 瓦尔细剑
--------
单手剑
物理伤害: 22-87
火焰，冰霜，闪电伤害: 5-87 (augmented)
暴击几率: 6.50%
每秒攻击次数: 1.30
武器范围: 14
--------
需求:
等级: 66
敏捷: 212 (unmet)
--------
插槽: G 
--------
物品等级: 74
--------
{ 基底词缀— 伤害, 物理, 攻击, 异常状态 }
流血伤害提高 15(14-18)% (implicit)
--------
{ ▲ 前缀词缀 "战斗的" (等阶：2)— 攻击, 宝石 }
此物品上装备的【近战技能石】等级 +1
{ ▲ 前缀词缀 "火花的" (等阶：6)— 伤害, 元素, 闪电, 攻击 }
该装备附加 5(4-5) - 87(80-94) 基础闪电伤害
{ ▽ 后缀词缀 "愤怒之" (等阶：5)— 伤害, 暴击 }
+18(15-19)% 全域暴击伤害加成
{ ▽ 后缀词缀 "逆渗透之" (等阶：2)— 魔力 }
每击败一名敌人获得2(2-3)点魔力
--------
忆境物品

**Comment by Traveller-hongchen** [comment]
找到了原因，下版本修
