### ISSUE TITLE
赛季载入失败

### ISSUE THREAD

**Issue by passseur** [Traveller-hongchen/Awakened-PoE-Trade-Simplified-Chinese#9]
![image](https://github.com/Traveller-hongchen/Awakened-PoE-Trade-Simplified-Chinese/assets/143065290/080ec756-3e79-4cc1-825a-aa7436124ce0)
![image](https://github.com/Traveller-hongchen/Awakened-PoE-Trade-Simplified-Chinese/assets/143065290/ef250a57-555f-4c6e-ada6-00af81b67f1b)
这个情况怎么解决？

**Comment by Traveller-hongchen** [comment]
国服的话，poesessid检查是否过期、有空格、填完是否先点了一下保存
